apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: db
data:
  PGDB_HOST: postgres.db.svc.cluster.local
  PGDB_USER: myuser
  PGDB_NAME: mydb
  REDIS_HOST: redis.redis.svc.cluster.local

