apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: PGDB_HOST
              value: "{{ .Values.env.PGDB_HOST }}"
            - name: PGDB_USER
              value: "{{ .Values.env.PGDB_USER }}"
            - name: PGDB_PASSWORD
              value: "{{ .Values.env.PGDB_PASSWORD }}"
            - name: PGDB_NAME
              value: "{{ .Values.env.PGDB_NAME }}"
            - name: REDIS_HOST
              value: "{{ .Values.env.REDIS_HOST }}"

